import { validarEmail, mitjana } from "./llibreries.js";
//EXERCICI 1 TONI!!!
console.log("EXERCICI 1:");
console.log("correcte");
validarEmail("egarcia@almata.cat");
validarEmail("hola@gmail.com");
validarEmail("");
validarEmail(1);
validarEmail();
validarEmail({});

console.log("************************");
console.log("@gmail.com");
validarEmail("@gmail.com");
console.log("************************");
console.log("holagmail.com");
validarEmail("holagmail.com");
console.log("************************");
console.log("NUMEROS");
validarEmail(123);
console.log("************************");
console.log("NULL");
validarEmail(null);
console.log("************************");
console.log("EXERCICI 2:");
console.log("************************");
console.log("[1, 2, 3, 4, 5]");
mitjana([1, 2, 3, 4, 5]);
console.log("************************");
console.log("[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]");
mitjana([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]);
console.log("************************");
console.log("SENSE PARAMETRE");
mitjana();
console.log("************************");
console.log("STRING");
mitjana("holaa");
console.log("************************");
console.log("NUMEROS");
mitjana(9999);
console.log("************************");
console.log("UNDEFINED");
mitjana(undefined);
console.log("************************");
mitjana(["aissam", "bouazama"]);
mitjana();
